### ISSUE TITLE
Unable to update UI

### ISSUE THREAD

**Issue by vietde** [tronikos/home-assistant-addons#33]
Hi,
I ran the update for latest UI. It's updated after the reboot but when I restart the docker container. It went back to the original UI version. Can you fix it?

**Comment by tronikos** [comment]
This is intentional to minimize backups. Just wait for the official updated docker image to be released. The repository will automatically detect any new version and automatically point to the latest official docker image, e.g. https://github.com/tronikos/home-assistant-addons/pull/32
